@Restaurants.API_HostAddress = https://localhost:7260

@RestaurantsAPI_HostAddress = https://localhost:7260
@token = CfDJ8BsCOi7EfI5IgQ9VAz0tW4Kg5bHs6EkLhO8a3Ybdxbi_CFdPDDAXluGhLC3VdmVOw2eOL6TY42bXo-r-qjFDbncdVOblva3fRS8qBX_4hM2QDDkgcy-cx4aJGu_1Yv6zZ4_nmGpeFo15PgHlJDAJts6U7r5Gn5Vb0UKdCKuIvMw45PFKI0QXmcOW1295VSJuzMdPQu08tbClUqpFQLmOvSebVTo8VvciwnA62IJRt_F-j9OmHx8cV9VynoZNDuaaRJ8mKQpwWy1PRIRszZJFcOSjzywlu48fLrtPhcntD0lkjkrwCIsHOOizP-jVY8nzlYRniSqG5RkPjGhgTz0xuajLeUrQ44SB0OIHc5H7hxetrD5m8_Doc9HC282ZK7e-1_MZbsjNM8W97MKvOO1hCwlIqNSOXtVujloD0dqzY69KJN7_nrhg0ImoxCMW4VTxcgXoOG_85i_a1RNhQT8p8WBuGMj8xrM3sziJH6LEz-grj5eiVT99jQ3GTX_Q_dIhHeUbf5wVGtGzMDzaSm_4zr1mpu9miGVsJdEzD4Du9jHtxeLPEKkveFkULQLXvvAL3Xsab_xxLjoePq86uLvfr21sFJIY80rgV9dPswALFbHSa-9wm4szJrmCQKveflrJWPQ_XopyFRi_Pm8SfLw_Wxp3EqERVYqyGkWTKqppDT4bo7Mzi31c5dDV1P1US_u3_pi9jvBKDSlhjyUYdA4z0-PpFZ56UA3A3ktn7cjhzYqp586dALXiJq8roo5vXnVZdq81TALwZoZEzc2sf-uhLYdPlQBW3LCeHzY1Vb3jbdLaTTBAr-wKvc0MupyWtUWd7pBTzbSCOIDa9GQZxYPv_aty1Z9qZQGguBRxdVPMkcjC41-JUQssXwkH6sqB0t-UQg



GET {{RestaurantsAPI_HostAddress}}/api/restaurants

###

GET {{RestaurantsAPI_HostAddress}}/api/restaurants/1
Authorization: Bearer {{token}}

###
POST {{RestaurantsAPI_HostAddress}}/api/restaurants
Content-type: application/json

{
    "Name": "Gourmet Paradiseededassdad",
    "Description": "A fine dining restaurant specializing in French cuisine.",
    "Category": "American",
    "HasDelivery": true,
    "ContactEmail": "contact@gourmetparadise.com",
    "ContactNumber": "+1 555-123-4567",
    "City": "Paris",
    "Street": "Champs-Élysées",
    "PostalCode": "75-008"
}

###
POST {{RestaurantsAPI_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-type: application/json

{
    "Name": "Savoy",
    "Description": "A fine dining restaurant specializing in French cuisine.",
    "Category": "American",
    "HasDelivery": true,
    "ContactEmail": "mail@mail.com",
    "ContactNumber": "sdfsdfsd",
    "City": "Paris",
    "Street": "Champs-Élysées",
    "PostalCode": "75-348"
}

###

GET {{RestaurantsAPI_HostAddress}}/api/restaurants/3

###

DELETE {{RestaurantsAPI_HostAddress}}/api/restaurants/3

###

PATCH {{RestaurantsAPI_HostAddress}}/api/restaurants/4
Content-Type: application/json

{
   "Name": "Savoy",
    "Description": "A fine dining restaurant specializing in French cuisine.",
    "HasDelivery": false
}

###

    
POST {{RestaurantsAPI_HostAddress}}/api/restaurant/2/dishes
Content-Type: application/json

{
  "name": "Fried chicken",
  "description": "Nashville Fried Chicken (10 pcs.)",
  "price": 10
}

###

GET {{RestaurantsAPI_HostAddress}}/api/restaurant/1/dishes

###

GET {{RestaurantsAPI_HostAddress}}/api/restaurant/1/dishes/3

###

DELETE {{RestaurantsAPI_HostAddress}}/api/restaurant/1/dishes

###
GET https://localhost:7260/api/restaurant/2/dishes/5

###

POST {{RestaurantsAPI_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "Example1234!"
}

###

POST {{RestaurantsAPI_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "user@gmail.com",
  "password": "Example1234!"
}

###

PATCH {{RestaurantsAPI_HostAddress}}/api/identity/user
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "DateOfBirth": "1995-10-23",
  "Nationality": "Argentinian"
}

###
